name: Android Master

on:
  push:
    branches:
      - 'master'

jobs:

  test:
    name: Upload to Bintray
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Upload to bintray
        env: # Or as an environment variable
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: bash echo $BINTRAY_USER && ./gradlew clean build bintrayUpload